# Generated by Django 6.0.6 on 2026-06-12 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TUK Bursary Application Form', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('form_file', models.FileField(upload_to='form_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('qualified', 'Qualified'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('vulnerability_details', models.TextField(help_text='Describe your financial vulnerability or hardship situation.')),
                ('family_background', models.TextField(help_text='Briefly describe your family background and financial situation.')),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of financial support requested (KES).', max_digits=10, null=True)),
                ('supporting_documents', models.FileField(blank=True, help_text='ID copy, fee statement, school letter, etc.', null=True, upload_to='applications/supporting/')),
                ('filled_form', models.FileField(blank=True, help_text='Completed application form (PDF or Word).', null=True, upload_to='applications/filled_forms/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes by the bursary committee (not visible to student).')),
                ('feedback_to_student', models.TextField(blank=True, default='', help_text='Message displayed to the student about their application decision.')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='application_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
