# Generated by Django on 2026-06-29

import io
from django.db import migrations
from django.core.files.base import ContentFile

def create_default_template(apps, schema_editor):
    title = 'Official TUK Bursary Application Form'
    description = (
        'This is the official Technical University of Kenya Bursary & Scholarship '
        'Application Form. Please download this form, complete all sections clearly (including '
        'financial details and family background), sign it, and upload the scanned file back '
        'through the submit page along with supporting documents.'
    )
    
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        
        doc = Document()
        
        # Margins
        for section in doc.sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)
            
        # Title
        p = doc.add_paragraph()
        run = p.add_run("THE TECHNICAL UNIVERSITY OF KENYA")
        run.bold = True
        run.font.size = Pt(16)
        run.font.color.rgb = RGBColor(13, 31, 60) # TUK Navy
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        p2 = doc.add_paragraph()
        run2 = p2.add_run("OFFICIAL BURSARY & SCHOLARSHIP APPLICATION FORM")
        run2.bold = True
        run2.font.size = Pt(14)
        run2.font.color.rgb = RGBColor(139, 26, 26) # Maroon
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph("\nInstructions: Please fill this form completely in block letters.")
        
        # Section A
        h1 = doc.add_paragraph()
        h1_run = h1.add_run("Section A: Personal & Academic Details")
        h1_run.bold = True
        h1_run.font.size = Pt(12)
        h1_run.font.color.rgb = RGBColor(13, 31, 60)
        
        doc.add_paragraph("1. Full Name: __________________________________________________")
        doc.add_paragraph("2. Registration Number: ___________________  3. Year of Study: ______")
        doc.add_paragraph("4. Department / Course: _________________________________________")
        doc.add_paragraph("5. Contact Phone Number: _________________  6. TUK Student Email: _______________________")
        
        # Section B
        h2 = doc.add_paragraph()
        h2_run = h2.add_run("Section B: Family Background & Vulnerability")
        h2_run.bold = True
        h2_run.font.size = Pt(12)
        h2_run.font.color.rgb = RGBColor(13, 31, 60)
        
        doc.add_paragraph("1. Parent/Guardian Status: [ ] Married  [ ] Single Parent  [ ] Orphaned")
        doc.add_paragraph("2. Total Family Income (Monthly): KES __________________")
        doc.add_paragraph("3. Explain financial challenges / hardship situations in detail below:")
        doc.add_paragraph("\n\n\n\n\n\n")
        
        # Section C
        h3 = doc.add_paragraph()
        h3_run = h3.add_run("Section C: Declaration")
        h3_run.bold = True
        h3_run.font.size = Pt(12)
        h3_run.font.color.rgb = RGBColor(13, 31, 60)
        
        doc.add_paragraph("I declare that the information provided above is true to the best of my knowledge.")
        doc.add_paragraph("\nSignature: __________________________  Date: ____________________")
        
        doc_io = io.BytesIO()
        doc.save(doc_io)
        doc_io.seek(0)
        file_content = doc_io.read()
        file_name = 'TUK_Bursary_Application_Form.docx'
    except Exception as e:
        # Fallback to simple txt
        text_content = (
            "THE TECHNICAL UNIVERSITY OF KENYA\n"
            "OFFICIAL BURSARY & SCHOLARSHIP APPLICATION FORM\n"
            "================================================\n\n"
            "Section A: Personal & Academic Details\n"
            "1. Full Name:\n"
            "2. Registration Number:\n"
            "3. Course / Programme:\n"
            "4. Year of Study:\n"
            "5. Phone Number:\n\n"
            "Section B: Family Background & Hardship Statement\n"
            "Please describe your family background and financial vulnerability situation.\n\n"
            "Section C: Declaration\n"
            "I declare that the information provided above is true.\n"
            "Signature:\n"
            "Date:\n"
        )
        file_content = text_content.encode('utf-8')
        file_name = 'TUK_Bursary_Application_Form.txt'
        
    ApplicationFormTemplate = apps.get_model('applications', 'ApplicationFormTemplate')
    # Deactivate existing active ones
    ApplicationFormTemplate.objects.filter(is_active=True).update(is_active=False)
    
    # Create the template object
    template = ApplicationFormTemplate(
        title=title,
        description=description,
        is_active=True
    )
    template.form_file.save(file_name, ContentFile(file_content), save=True)

def remove_default_template(apps, schema_editor):
    ApplicationFormTemplate = apps.get_model('applications', 'ApplicationFormTemplate')
    # Just delete templates created under this name
    ApplicationFormTemplate.objects.filter(title='Official TUK Bursary Application Form').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_template, reverse_code=remove_default_template),
    ]
