# Generated by Django 6.0.3 on 2026-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Application Form', max_length=200)),
                ('form_file', models.FileField(upload_to='form_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='filled_form',
            field=models.FileField(blank=True, null=True, upload_to='applications/filled_forms/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='applications/supporting/'),
        ),
    ]
